using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.EventSystems;

namespace UnityEssentials.UI
{
    /// <summary>
    /// One loaded window: an overlay canvas, one instance of every screen, popup and panel its
    /// <see cref="WindowData"/> listed — all parented directly under the window GameObject — and the
    /// widget prototypes it can spawn from. Generated by <see cref="WindowData.GenerateWindow"/> and
    /// filled by <see cref="LoadWindow"/>; do not add this component by hand.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class UIWindow : MonoBehaviour
    {
        private static bool _eventSystemWarningIssued;

        private readonly List<UIBase> _elements = new List<UIBase>();
        private readonly Dictionary<Type, UIBase> _elementsByType = new Dictionary<Type, UIBase>();
        private readonly Dictionary<Type, GameObject> _widgetPrototypes = new Dictionary<Type, GameObject>();
        private readonly List<WidgetBase> _spawnedWidgets = new List<WidgetBase>();

        public WindowData Data { get; internal set; }

        public WindowService Service { get; private set; }

        public Canvas Canvas { get; internal set; }

        public IReadOnlyList<UIBase> Elements => _elements;

        public IReadOnlyList<WidgetBase> SpawnedWidgets => _spawnedWidgets;

        /// <summary>
        /// Loads this window for <paramref name="service"/>: instantiates one bound, deactivated
        /// instance of every UI prefab and registers the widget prototypes. Runs exactly once.
        /// </summary>
        public void LoadWindow(WindowService service)
        {
            if (service == null)
            {
                throw new ArgumentNullException(nameof(service));
            }

            if (Data == null)
            {
                throw new WindowConfigurationException(
                    $"Window '{name}' has no WindowData, so it was not created through " +
                    "WindowData.GenerateWindow. Never add the UIWindow component by hand — call " +
                    "WindowService.SwitchWindow and let the service generate and load the window.");
            }

            if (Service != null)
            {
                throw new WindowConfigurationException(
                    $"Window '{name}' is already loaded and a window loads exactly once. To rebuild it, " +
                    "unload it and generate a fresh window — which is what WindowService.SwitchWindow does.");
            }

            Service = service;
            LoadElements();
            RegisterWidgetPrototypes();
            WarnIfNoEventSystem();
        }

        /// <summary>
        /// Unloads everything this window created — spawned widgets first, wherever they were
        /// parented — releases the loaded references and destroys the window GameObject.
        /// </summary>
        public void UnloadWindow()
        {
            // The service has already hidden screens, popups and panels; widgets are the exception —
            // one spawned under an external parent is not a child of this window and must be torn
            // down here or it would outlive its canvas.
            var widgets = _spawnedWidgets.ToArray();

            for (var i = 0; i < widgets.Length; i++)
            {
                var widget = widgets[i];
                if (widget == null)
                {
                    continue;
                }

                widget.Hide();
                SafeDestroy(widget.gameObject);
            }

            _spawnedWidgets.Clear();
            _elements.Clear();
            _elementsByType.Clear();
            _widgetPrototypes.Clear();

            SafeDestroy(gameObject);
        }

        /// <summary>Returns this window's instance of <typeparamref name="T"/>, or throws naming what it does carry.</summary>
        public UIBase GetUI<T>() where T : UIBase
        {
            return GetUI(typeof(T));
        }

        /// <summary>Returns this window's instance of <paramref name="uiType"/>, or throws naming what it does carry.</summary>
        public UIBase GetUI(Type uiType)
        {
            if (uiType == null)
            {
                throw new ArgumentNullException(nameof(uiType));
            }

            if (_elementsByType.TryGetValue(uiType, out var element))
            {
                return element;
            }

            if (_widgetPrototypes.ContainsKey(uiType) || typeof(UIWidget).IsAssignableFrom(uiType))
            {
                throw new UIElementNotFoundException(
                    $"'{uiType.Name}' is a widget, not a UI element — widgets are spawned, not resolved. " +
                    $"Use GetWidget<{uiType.Name}>() and hand the instance back with ReturnWidget when you " +
                    "are done with it.");
            }

            throw new UIElementNotFoundException(
                $"Window '{name}' has no UI element of type '{uiType.Name}'. It carries: {DescribeElements()}. " +
                "Add the prefab to the UI Prefabs list of the WindowData this window was built from, or switch " +
                "to the window that owns it.");
        }

        /// <summary>Tries to resolve <paramref name="uiType"/>, returning false instead of throwing on a miss.</summary>
        public bool TryGetUI(Type uiType, out UIBase ui)
        {
            if (uiType == null)
            {
                ui = null;
                return false;
            }

            return _elementsByType.TryGetValue(uiType, out ui);
        }

        /// <summary>
        /// Spawns a widget from this window's prototype for <paramref name="widgetType"/>, parents
        /// it (null means this window), binds it, tracks it and shows it.
        /// </summary>
        public WidgetBase GetWidget(Type widgetType, Transform parent, IUIData uiData)
        {
            if (widgetType == null)
            {
                throw new ArgumentNullException(nameof(widgetType));
            }

            if (!_widgetPrototypes.TryGetValue(widgetType, out var prefab))
            {
                throw new UIElementNotFoundException(
                    $"Window '{name}' cannot spawn widget type '{widgetType.Name}': no prefab is registered for " +
                    $"it. It can spawn: {DescribeWidgets()}. Add the prefab to the Widgets list of the WindowData " +
                    "this window was built from — the UI Prefabs list is for screens, popups and panels, which " +
                    "are instantiated once at load rather than spawned.");
            }

            // Unity's overloaded comparison: a destroyed parent counts as null.
            var container = parent != null ? parent : transform;

            var instance = Instantiate(prefab, container, false);
            var widget = instance.GetComponent<WidgetBase>();

            widget.Bind(this);
            _spawnedWidgets.Add(widget);
            widget.Show(uiData);

            return widget;
        }

        /// <summary>Takes a spawned widget back: hides it, stops tracking it and destroys it.</summary>
        public void ReturnWidget(WidgetBase widget)
        {
            if (widget == null)
            {
                throw new ArgumentNullException(nameof(widget));
            }

            if (IndexOfWidget(widget) < 0)
            {
                throw new UIBindingException(
                    $"Widget '{widget.GetType().Name}' was not spawned by window '{name}', or has already been " +
                    "returned, so this window cannot take it back. Return a widget through the same service and " +
                    "window that spawned it, and exactly once.");
            }

            widget.Hide();

            // Located again after the hide: OnHide is consumer code and may return other widgets.
            var index = IndexOfWidget(widget);
            if (index >= 0)
            {
                _spawnedWidgets.RemoveAt(index);
            }

            // Destruction is the v1 return path; a pooling mechanism would reclaim the instance here.
            SafeDestroy(widget.gameObject);
        }

        internal static void SafeDestroy(UnityEngine.Object target)
        {
            if (target == null)
            {
                return;
            }

            if (Application.isPlaying)
            {
                Destroy(target);
            }
            else
            {
                // Outside play mode a queued Destroy never runs (no frame end), and DestroyImmediate
                // is forbidden during play — hence the split.
                DestroyImmediate(target);
            }
        }

        private void LoadElements()
        {
            var prefabs = Data.UIPrefabs;

            for (var i = 0; i < prefabs.Count; i++)
            {
                var prefab = prefabs[i];
                if (prefab == null)
                {
                    throw new WindowConfigurationException(
                        $"WindowData '{Data.name}' has a null entry in UI Prefabs at index {i}. This should have " +
                        "been caught by WindowData.ThrowIfInvalid before the window was built; call SwitchWindow " +
                        "rather than generating and loading a window directly.");
                }

                var prototype = prefab.GetComponent<UIBase>();
                if (prototype == null)
                {
                    throw new WindowConfigurationException(
                        $"WindowData '{Data.name}' has prefab '{prefab.name}' in UI Prefabs at index {i} with no " +
                        "UI component on its root. This should have been caught by WindowData.ThrowIfInvalid " +
                        "before the window was built; call SwitchWindow rather than generating and loading a " +
                        "window directly.");
                }

                // Instantiated active then deactivated, so Awake/OnEnable run exactly once at load.
                // Everything is parented straight under the window; sibling order is authored order.
                var instance = Instantiate(prototype, transform, false);
                instance.Bind(this);
                instance.gameObject.SetActive(false);

                _elements.Add(instance);
                _elementsByType[instance.GetType()] = instance;
            }
        }

        private void RegisterWidgetPrototypes()
        {
            var widgets = Data.Widgets;

            for (var i = 0; i < widgets.Count; i++)
            {
                var entry = widgets[i];
                var prefab = entry != null ? entry.Prefab : null;
                var prototype = prefab != null ? prefab.GetComponent<WidgetBase>() : null;

                if (prototype == null)
                {
                    throw new WindowConfigurationException(
                        $"WindowData '{Data.name}' has an entry in Widgets at index {i} with no prefab, or with a " +
                        "prefab carrying no WidgetBase component on its root. This should have been caught by " +
                        "WindowData.ThrowIfInvalid before the window was built; call SwitchWindow rather than " +
                        "generating and loading a window directly.");
                }

                _widgetPrototypes[prototype.GetType()] = prefab;
            }
        }

        private int IndexOfWidget(WidgetBase widget)
        {
            for (var i = 0; i < _spawnedWidgets.Count; i++)
            {
                if (ReferenceEquals(_spawnedWidgets[i], widget))
                {
                    return i;
                }
            }

            return -1;
        }

        private string DescribeElements()
        {
            if (_elements.Count == 0)
            {
                return "nothing — its WindowData lists no UI prefabs";
            }

            var builder = new StringBuilder();

            for (var i = 0; i < _elements.Count; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(_elements[i].GetType().Name);
            }

            return builder.ToString();
        }

        private string DescribeWidgets()
        {
            if (_widgetPrototypes.Count == 0)
            {
                return "nothing — its WindowData lists no widgets";
            }

            var builder = new StringBuilder();

            foreach (var prototype in _widgetPrototypes)
            {
                if (builder.Length > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(prototype.Key.Name);
            }

            return builder.ToString();
        }

        private static void WarnIfNoEventSystem()
        {
            if (_eventSystemWarningIssued || !Application.isPlaying || EventSystem.current != null)
            {
                return;
            }

            _eventSystemWarningIssued = true;

            Debug.LogWarning(
                "UI system: a window was loaded but the scene has no EventSystem, so no UI element will receive " +
                "clicks, taps or navigation input. Add one via GameObject > UI > Event System, with the input " +
                "module that matches your project's input backend — InputSystemUIInputModule for the Input System " +
                "package, StandaloneInputModule for the legacy input manager. The UI system never creates one " +
                "itself: it cannot know which module is correct, and picking the wrong one silently kills all UI " +
                "input rather than failing loudly.");
        }

        // Needed because Enter Play Mode Options can skip the domain reload that would reset statics.
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void ResetWarningState()
        {
            _eventSystemWarningIssued = false;
        }
    }
}
