using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using UnityEditor;

namespace NvimUnity.Editor
{

    // SDK-style csproj generation. Inherits everything from ClassicProjectGenerator and
    // overrides only the per-project file content. Unity hands us the full reference set as
    // absolute HintPaths, which is why the implicit-reference properties below are all off.
    public class RoslynProjectGenerator : ClassicProjectGenerator
    {
        public RoslynProjectGenerator(string projectDirectory) : base(projectDirectory)
        {
        }

        // Empty or "auto" config: take the framework from the assembly's API compatibility level.
        private static string ResolveTargetFramework(ProjectPart assembly)
        {
            var cfg = NvimUnityConfig.instance.TargetFramework;
            if (!string.IsNullOrWhiteSpace(cfg) && !cfg.Trim().Equals("auto", StringComparison.OrdinalIgnoreCase))
                return cfg.Trim();
    #if UNITY_2020_2_OR_NEWER
            if (assembly.CompilerOptions.ApiCompatibilityLevel == ApiCompatibilityLevel.NET_Standard_2_0)
                return "netstandard2.1";
    #endif
            return "net471";
        }

        // Empty, "latest" or "auto" config: use Unity's own compiler language version.
        private string ResolveLangVersion(ILookup<string, string> responseFileArgs, ProjectPart assembly)
        {
            var cfg = NvimUnityConfig.instance.LangVersion;
            if (!string.IsNullOrWhiteSpace(cfg))
            {
                var trimmed = cfg.Trim();
                if (!trimmed.Equals("latest", StringComparison.OrdinalIgnoreCase)
                    && !trimmed.Equals("auto", StringComparison.OrdinalIgnoreCase))
                    return trimmed;
            }
            return GetLangVersion(responseFileArgs["langversion"], assembly);
        }

        protected override string BuildProjectFileContent(StringBuilder stringBuilder, ProjectPart assembly, AssemblyUsage assemblyUsage)
        {
            var responseFileDatas = assembly.GetResponseFileData(ProjectDirectory);
            var responseFileArgs = GetOtherArgumentsFromResponseFilesData(responseFileDatas);

            var hasPlayerAssemblyFlag = !ProjectGenerationFlag.HasFlag(ProjectGenerationFlag.PlayerAssemblies);
            var projFileName = !hasPlayerAssemblyFlag ? assembly.Name :
                !assembly.Defines.Contains("UNITY_EDITOR") ? assembly.Name + ".Player" : assembly.Name;

            var defines = new HashSet<string>(assembly.Defines);
            foreach (var responseFileData in responseFileDatas)
                defines.UnionWith(responseFileData.Defines);

            stringBuilder
                .AppendLine("<!-- Generated by NvimUnity RoslynProjectGenerator (SDK-style) -->")
                .AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">")
                .AppendLine("  <PropertyGroup>")
                .Append("    <TargetFramework>").Append(ResolveTargetFramework(assembly)).AppendLine("</TargetFramework>")
                .Append("    <LangVersion>").Append(ResolveLangVersion(responseFileArgs, assembly)).AppendLine("</LangVersion>")
                .AppendLine("    <EnableDefaultItems>false</EnableDefaultItems>")
                .AppendLine("    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>")
                .AppendLine("    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>")
                .AppendLine("    <NoStdLib>true</NoStdLib>")
                .AppendLine("    <NoConfig>true</NoConfig>")
                .AppendLine("    <ImplicitUsings>disable</ImplicitUsings>")
                .Append("    <RootNamespace>").Append(assembly.RootNamespace).AppendLine("</RootNamespace>")
                .Append("    <AssemblyName>").Append(assembly.Name).AppendLine("</AssemblyName>")
                .AppendLine("    <OutputType>Library</OutputType>")
                .Append("    <OutputPath>").Append(assembly.OutputPath).AppendLine("</OutputPath>")
                .Append("    <BaseIntermediateOutputPath>Temp\\Obj\\").Append(projFileName).AppendLine("\\</BaseIntermediateOutputPath>")
                .Append("    <IntermediateOutputPath>Temp\\Obj\\").Append(projFileName).AppendLine("\\</IntermediateOutputPath>")
                .AppendLine("    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>")
                .AppendLine("    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>")
                .AppendLine("    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>")
                .Append("    <DefineConstants>").CompatibleAppendJoin(';', defines).AppendLine("</DefineConstants>");

            var warningLevel = responseFileArgs["warn"].Concat(responseFileArgs["w"]).Distinct().FirstOrDefault();
            stringBuilder
                .Append("    <WarningLevel>").Append(!string.IsNullOrWhiteSpace(warningLevel) ? warningLevel : "4").AppendLine("</WarningLevel>")
                .Append("    <NoWarn>").CompatibleAppendJoin(',', GetNoWarn(responseFileArgs["nowarn"].ToList())).AppendLine("</NoWarn>")
                .Append("    <AllowUnsafeBlocks>").Append(assembly.CompilerOptions.AllowUnsafeCode | responseFileDatas.Any(x => x.Unsafe)).AppendLine("</AllowUnsafeBlocks>");

            AppendWarningAsError(stringBuilder, responseFileArgs["warnaserror"], responseFileArgs["warnaserror-"], responseFileArgs["warnaserror+"]);

            foreach (var docFile in responseFileArgs["doc"])
                stringBuilder.Append("    <DocumentationFile>").Append(docFile).AppendLine("</DocumentationFile>");

            var nullable = responseFileArgs["nullable"].FirstOrDefault();
            if (!string.IsNullOrEmpty(nullable))
                stringBuilder.Append("    <Nullable>").Append(nullable).AppendLine("</Nullable>");

            var rulesetPaths = new HashSet<string>(responseFileArgs["ruleset"]);
    #if UNITY_2020_2_OR_NEWER
            if (!string.IsNullOrEmpty(assembly.CompilerOptions.RoslynAnalyzerRulesetPath))
                rulesetPaths.Add(assembly.CompilerOptions.RoslynAnalyzerRulesetPath);
    #endif
            foreach (var path in rulesetPaths.Select(GetNormalisedAssemblyPath))
                stringBuilder.Append("    <CodeAnalysisRuleSet>").Append(path).AppendLine("</CodeAnalysisRuleSet>");

            stringBuilder.AppendLine("  </PropertyGroup>");

            var analyzers = GetRoslynAnalyzers(assembly, responseFileArgs);
            if (analyzers.Length > 0)
            {
                stringBuilder.AppendLine("  <ItemGroup>");
                foreach (var analyzer in analyzers)
                    stringBuilder.AppendLine($"    <Analyzer Include=\"{analyzer.NormalizePath()}\" />");
                stringBuilder.AppendLine("  </ItemGroup>");
            }

            var additionalFiles = GetRoslynAdditionalFiles(assembly, responseFileArgs);
            if (additionalFiles.Length > 0)
            {
                stringBuilder.AppendLine("  <ItemGroup>");
                foreach (var additionalFile in additionalFiles)
                    stringBuilder.AppendLine($"    <AdditionalFiles Include=\"{additionalFile}\" />");
                stringBuilder.AppendLine("  </ItemGroup>");
            }

            var configFile = GetGlobalAnalyzerConfigFile(assembly);
            if (!string.IsNullOrEmpty(configFile))
            {
                stringBuilder
                    .AppendLine("  <ItemGroup>")
                    .Append("    <GlobalAnalyzerConfigFiles Include=\"").Append(configFile).AppendLine("\" />")
                    .AppendLine("  </ItemGroup>");
            }

            // Explicit Compile items, same shape as classic so the nvim-side csproj patcher
            // works on either generator's output.
            stringBuilder.AppendLine("  <ItemGroup>");
            foreach (var file in assembly.SourceFiles)
            {
                var absPath = Path.GetFullPath(file.NormalizePath());
                var path = NvimEditorUtils.SkipPathPrefix(absPath, ProjectDirectory);
                stringBuilder.Append("    <Compile Include=\"").Append(SecurityElement.Escape(path)).AppendLine("\" />");
            }

            var additionals = (IEnumerable<string>)assembly.AdditionalAssets ?? Array.Empty<string>();
            foreach (var additionalAsset in additionals)
                stringBuilder.Append("    <None Include=\"").Append(additionalAsset).AppendLine("\" />");

            var binaryReferences = new HashSet<string>(assembly.CompiledAssemblyReferences);
            foreach (var responseFileData in responseFileDatas)
                binaryReferences.UnionWith(responseFileData.FullPathReferences);

            foreach (var assemblyReference in assembly.AssemblyReferences)
            {
                if (assemblyUsage.IsPrecompiledAssembly(assemblyReference))
                    binaryReferences.Add(assemblyReference.outputPath);
            }

            foreach (var reference in binaryReferences)
            {
                stringBuilder
                    .Append("    <Reference Include=\"").Append(GetAssemblyNameFromPath(reference)).AppendLine("\">")
                    .Append("      <HintPath>").Append(GetNormalisedAssemblyPath(reference)).AppendLine("</HintPath>")
                    .AppendLine("      <Private>false</Private>")
                    .AppendLine("    </Reference>");
            }

            if (0 < assembly.AssemblyReferences.Length)
            {
                stringBuilder
                    .AppendLine("  </ItemGroup>")
                    .AppendLine("  <ItemGroup>");
                foreach (var reference in assembly.AssemblyReferences)
                {
                    if (assemblyUsage.IsProjectAssembly(reference))
                    {
                        var referenceName = !hasPlayerAssemblyFlag ? reference.name :
                            !assembly.Defines.Contains("UNITY_EDITOR") ? reference.name + ".Player" : reference.name;
                        stringBuilder
                            .Append("    <ProjectReference Include=\"").Append(referenceName).AppendLine(".csproj\" />");
                    }
                }
            }

            stringBuilder
                .AppendLine("  </ItemGroup>")
                .AppendLine("</Project>");

            return stringBuilder.ToString();
        }
    }
}
